language: node_js

node_js:
  - "8"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn add --dev codecov

script:
  - codecov

cache: yarn
